version: "2"
services:
  web:
    image: mcahill7/todoapp
    cpu_shares: 50
    ports:
      - "3000:3000"
      - "80:80"
      - "8080:8080"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
